### ISSUE TITLE
Encoding check seems invalid

### ISSUE THREAD

**Issue by lkhaas** [acquia/http-hmac-javascript#7]
The check for encoding added in version 2.0 appears to be invalid
https://github.com/acquia/http-hmac-javascript/blob/master/src/hmac.js#L268

Any encoded variables end up double-encoded
For example:  passing in:
http://localhost:5050/rules?account_id=D8DEMO&site_id=DFSITEDEV&status=-archived&visible_on_page=http%3A%2F%2Flocalhost%3A4200%2Ftests%3Fmodule%3DAcceptance%2520%257C%2520authentication&sort=asc&sort_field=weight

Produces the following when run through encodeURI(decodeURI(path))
Note that the % is being encoded in the visible_on_page parameter.
http://localhost:5050/rules?account_id=D8DEMO&site_id=DFSITEDEV&status=-archived&visible_on_page=http%253A%252F%252Flocalhost%253A4200%252Ftests%253Fmodule%253DAcceptance%2520%257C%2520authentication&sort=asc&sort_field=weight

**Comment by ynx** [comment]
Attempted to fixed the incorrect checking, and decided to removed the check. This is because a proper check adds performance drag to every request. Fixed in 0.2.2.
