### ISSUE TITLE
Allow to use PATCH method

### ISSUE THREAD

**Issue by eduardoweiland** [acquia/http-hmac-javascript#9]
The `SUPPORTED_METHODS` array does not include the `PATCH` method and gives the following error when trying to sign a request that uses PATCH method:

    The method must be "GET" or "POST" or "PUT" or "DELETE" or "HEAD" or "OPTIONS" or "CUSTOM". "PATCH" is not supported.

PATCH is widely used in [JSON:API](http://jsonapi.org) specification. Can you provide support for this method?

**Comment by ynx** [comment]
Added support for PATCH in 0.2.4.
